### ISSUE TITLE
NullPointerException thrown by SimpleNoder when geometries intersect but do not overlap

### ISSUE THREAD

**Issue by mmcposs** [locationtech/jts#1009]
Using SimpleNoder with OverlayNG generates a null pointer exception when geometry intersects, but does not overlap.
NPE occurs with double floating point precision and fixed decimal precision.

Fixed decimal precision definition:
```
double precisionScale = 1e6;
PrecisionModel  PM = new PrecisionModel(precisionScale);
```

Double floating point precision definition:
```
PrecisionModel  PM = new PrecisionModel();
```

Differencing call:
```
SimpleNoder src = new SimpleNoder();
Geometry newGeometry = OverlayNG.overlay(baseGeometry, subtractionGeometry, OverlayNG.DIFFERENCE, PM, src);
```

Console output:
```
Base Geometry
POLYGON ((-100 39.99, -100.01 40, -100.01 40.1, -100 40.11, -99.9 40.11, -99.89 40.1, -99.89 40, -99.9 39.99, -100 39.99))

Subtraction Geometry
MULTIPOLYGON (((-100 40, -100 40.1, -99.9 40, -100 40)))

[ERROR] 2023-10-19 14:11:10:147
java.lang.NullPointerException: null
	at org.locationtech.jts.noding.SimpleNoder.computeIntersects(SimpleNoder.java:59) ~[jts-core-1.19.0.jar:?]
	at org.locationtech.jts.noding.SimpleNoder.computeNodes(SimpleNoder.java:48) ~[jts-core-1.19.0.jar:?]
	at org.locationtech.jts.operation.overlayng.EdgeNodingBuilder.node(EdgeNodingBuilder.java:186) ~[jts-core-1.19.0.jar:?]
	at org.locationtech.jts.operation.overlayng.EdgeNodingBuilder.build(EdgeNodingBuilder.java:165) ~[jts-core-1.19.0.jar:?]
	at org.locationtech.jts.operation.overlayng.OverlayNG.nodeEdges(OverlayNG.java:541) ~[jts-core-1.19.0.jar:?]
	at org.locationtech.jts.operation.overlayng.OverlayNG.computeEdgeOverlay(OverlayNG.java:495) ~[jts-core-1.19.0.jar:?]
	at org.locationtech.jts.operation.overlayng.OverlayNG.getResult(OverlayNG.java:483) ~[jts-core-1.19.0.jar:?]
	at org.locationtech.jts.operation.overlayng.OverlayNG.overlay(OverlayNG.java:229) ~[jts-core-1.19.0.jar:?]
```

JTS TestBuilder Screenshot of the Geometries:
![NPE with SimpleNoder](https://github.com/locationtech/jts/assets/16108280/7cff3485-b3d3-447a-9a2c-3602cedf135c)

**Comment by dr-jts** [comment]
You need to specify a `SegmentIntersector` using the [`setSegmentIntersector`](https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/noding/SinglePassNoder.java#L47) method.

I grant that this is not obvious.  Probably this should be enforced by requiring it in the constructor.
