### ISSUE TITLE
Geometry.union for fixed precision fails with TopologyException 

### ISSUE THREAD

**Issue by mr-tl** [locationtech/jts#288]
Hello,

calling Geometry.union on two polygons result in the following TopologyException:

```
Exception in thread "main" org.locationtech.jts.geom.TopologyException: found non-noded intersection between LINESTRING ( -24.99999892875 171.31732721485, -24.9999982443 71.51813717395 ) and LINESTRING ( -24.99999871375 139.9692190221, -25.0 139.9692190221 ) [ (-24.999998713756142, 139.9692190221, NaN) ]
	at org.locationtech.jts.noding.FastNodingValidator.checkValid(FastNodingValidator.java:127)
	at org.locationtech.jts.geomgraph.EdgeNodingValidator.checkValid(EdgeNodingValidator.java:78)
	at org.locationtech.jts.geomgraph.EdgeNodingValidator.checkValid(EdgeNodingValidator.java:43)
	at org.locationtech.jts.operation.overlay.OverlayOp.computeOverlay(OverlayOp.java:231)
	at org.locationtech.jts.operation.overlay.OverlayOp.getResultGeometry(OverlayOp.java:183)
	at org.locationtech.jts.operation.overlay.OverlayOp.overlayOp(OverlayOp.java:86)
	at org.locationtech.jts.operation.overlay.snap.SnapIfNeededOverlayOp.getResultGeometry(SnapIfNeededOverlayOp.java:75)
	at org.locationtech.jts.operation.overlay.snap.SnapIfNeededOverlayOp.overlayOp(SnapIfNeededOverlayOp.java:37)
	at org.locationtech.jts.geom.Geometry.union(Geometry.java:1406)
	at UnionFailure.main(UnionFailure.java:25)
```

A test for reproducing the error is as follows:

```
import org.locationtech.jts.geom.Geometry;
import org.locationtech.jts.geom.GeometryFactory;
import org.locationtech.jts.geom.PrecisionModel;
import org.locationtech.jts.io.ParseException;
import org.locationtech.jts.io.WKTReader;

public class UnionFailure {

    public static void main(String[] args) throws ParseException {

        final String i1 =
            "POLYGON ((-25 700, -25 327.5217935613, "
            + "-24.9999982443 71.51813717395, 2000 70, -25 700))";
        final String i2 =
            "POLYGON ((-24.9999998349 674.30377216845, "
            + "-25 674.30377216845, -24.99999893265 171.8884408023, "
            + "-24.99999871375 139.9692190221, -25 139.9692190221, "
            + "-25 20, 900 800, -25 700, -24.9999998349 674.30377216845))";

        final WKTReader reader =
            new WKTReader(new GeometryFactory(new PrecisionModel(2E10)));
        final Geometry p1 = reader.read(i1);
        final Geometry p2 = reader.read(i2);

        p1.union(p2);
    }
}
```

This was run on the latest release 1.15.0

Best regards,

Magnus

**Comment by mr-tl** [comment]
Ok thanks Martin! /Magnus

**Comment by dr-jts** [comment]
This is fixed by using OverlayNG with fixed-precision output:
```
PrecisionModel pm = new PrecisionModel(2E10);
OverlayNG.overlay(p1, p2, OverlayNG.UNION, pm);
```

<img width="967" alt="image" src="https://github.com/user-attachments/assets/6f7b7e26-4fac-462e-bdfb-1c2a81f4e3b3" />
