### ISSUE TITLE
Exceptions Thrown When Attempting to Split Polygon With Islands

### ISSUE THREAD

**Issue by Sarev0k** [locationtech/jts#303]
While attempting to follow the directions to split polygons from [this FAQ](https://locationtech.github.io/jts/jts-faq.html#E3), I ran into some issues performing difference and intersection operations on polygons containing islands.

### Attempted
Computation of the intersection and difference between the following polygons:
* `POLYGON ((-122.35284805297852 47.608362020408656, -122.31370925903322 47.608362020408656, -122.31370925903322 47.636477621161035, -122.35284805297852 47.636477621161035, -122.35284805297852 47.608362020408656), (-122.34718322753905 47.611255269744255, -122.34718322753905 47.63231330110795, -122.31800079345703 47.63231330110795, -122.31800079345703 47.611255269744255, -122.34718322753905 47.611255269744255), (-122.34169006347656 47.62259526372309, -122.34169006347656 47.627917269908, -122.33345031738283 47.627917269908, -122.33345031738283 47.62259526372309, -122.34169006347656 47.62259526372309), (-122.33036041259766 47.61310686532273, -122.32143402099608 47.61310686532273, -122.32143402099608 47.618429837435635, -122.33036041259766 47.618429837435635, -122.33036041259766 47.61310686532273))`
* `POLYGON ((-122.31370842756361 47.608361464838424, -122.33757019042969 47.62525626681555, -122.35284805297852 47.63647862116103, -122.31370925903322 47.63647862116103, -122.3137090639429 47.636478601946315, -122.31370887634978 47.63647854504057, -122.31370870346298 47.63647845263065, -122.31370855192644 47.63647832826781, -122.31370842756361 47.636478176731266, -122.31370833515369 47.636478003844466, -122.31370827824794 47.63647781625136, -122.31370825903322 47.636477621161035, -122.31370825903322 47.608362020408656, -122.31370827824794 47.60836182531833, -122.31370833515369 47.608361637725224, -122.31370842756361 47.608361464838424))`

### Expected Result
Multipolygon containing the half the outer polygon and half of each island.

### Actual Result
Intersection:
```
org.locationtech.jts.geom.TopologyException: Directed Edge visited twice during ring-building at (-122.34717747929284, 47.63231330110795, NaN)
	at org.locationtech.jts.geomgraph.EdgeRing.computePoints(EdgeRing.java:126)
	at org.locationtech.jts.geomgraph.EdgeRing.<init>(EdgeRing.java:53)
	at org.locationtech.jts.operation.overlay.MaximalEdgeRing.<init>(MaximalEdgeRing.java:48)
	at org.locationtech.jts.operation.overlay.PolygonBuilder.buildMaximalEdgeRings(PolygonBuilder.java:93)
	at org.locationtech.jts.operation.overlay.PolygonBuilder.add(PolygonBuilder.java:67)
	at org.locationtech.jts.operation.overlay.PolygonBuilder.add(PolygonBuilder.java:56)
	at org.locationtech.jts.operation.overlay.OverlayOp.computeOverlay(OverlayOp.java:250)
	at org.locationtech.jts.operation.overlay.OverlayOp.getResultGeometry(OverlayOp.java:183)
	at org.locationtech.jts.operation.overlay.OverlayOp.overlayOp(OverlayOp.java:86)
	at org.locationtech.jts.operation.overlay.snap.SnapIfNeededOverlayOp.getResultGeometry(SnapIfNeededOverlayOp.java:75)
	at org.locationtech.jts.operation.overlay.snap.SnapIfNeededOverlayOp.overlayOp(SnapIfNeededOverlayOp.java:37)
	at org.locationtech.jts.geom.Geometry.intersection(Geometry.java:1354)
```

Difference:
```
org.locationtech.jts.geom.TopologyException: Found null DirectedEdge
	at org.locationtech.jts.geomgraph.EdgeRing.computePoints(EdgeRing.java:124)
	at org.locationtech.jts.geomgraph.EdgeRing.<init>(EdgeRing.java:53)
	at org.locationtech.jts.operation.overlay.MaximalEdgeRing.<init>(MaximalEdgeRing.java:48)
	at org.locationtech.jts.operation.overlay.PolygonBuilder.buildMaximalEdgeRings(PolygonBuilder.java:93)
	at org.locationtech.jts.operation.overlay.PolygonBuilder.add(PolygonBuilder.java:67)
	at org.locationtech.jts.operation.overlay.PolygonBuilder.add(PolygonBuilder.java:56)
	at org.locationtech.jts.operation.overlay.OverlayOp.computeOverlay(OverlayOp.java:250)
	at org.locationtech.jts.operation.overlay.OverlayOp.getResultGeometry(OverlayOp.java:183)
	at org.locationtech.jts.operation.overlay.OverlayOp.overlayOp(OverlayOp.java:86)
	at org.locationtech.jts.operation.overlay.snap.SnapIfNeededOverlayOp.getResultGeometry(SnapIfNeededOverlayOp.java:75)
	at org.locationtech.jts.operation.overlay.snap.SnapIfNeededOverlayOp.overlayOp(SnapIfNeededOverlayOp.java:37)
	at org.locationtech.jts.geom.Geometry.difference(Geometry.java:1435)
```

Do you have any suggestions for how I might work around this issue?

Thanks

**Comment by dr-jts** [comment]
The first polygon is invalid.  As shown below, it contains nested holes.

![image](https://user-images.githubusercontent.com/3529053/216397587-b3f84fdd-8b01-4d48-b8ca-3a23a29ecb7e.png)

If the inner holes are converted to Polygons, the intersection works:
```
MULTIPOLYGON (((-122.35284805297852 47.608362020408656, -122.31370925903322 47.608362020408656, -122.31370925903322 47.636477621161035, -122.35284805297852 47.636477621161035, -122.35284805297852 47.608362020408656), (-122.34718322753905 47.611255269744255, -122.34718322753905 47.63231330110795, -122.31800079345703 47.63231330110795, -122.31800079345703 47.611255269744255, -122.34718322753905 47.611255269744255)), ((-122.34169006347656 47.62259526372309, -122.34169006347656 47.627917269908, -122.33345031738283 47.627917269908, -122.33345031738283 47.62259526372309, -122.34169006347656 47.62259526372309)), ((-122.33036041259766 47.61310686532273, -122.32143402099608 47.61310686532273, -122.32143402099608 47.618429837435635, -122.33036041259766 47.618429837435635, -122.33036041259766 47.61310686532273)))
```
![image](https://user-images.githubusercontent.com/3529053/216398163-9100f55c-90fb-459f-b1bd-1a3aade0d3e5.png)
