### ISSUE TITLE
Invalid number of points in LinearRing (found 3 - must be 0 or >= 4)

### ISSUE THREAD

**Issue by Cavva79** [locationtech/jts#558]
Hi all
I have a really bad geometry:
`
MULTIPOLYGON (((1764821.349985 4897058.789998, 1764821.349425 4897058.794803, 1764821.349985 4897058.789998)), ((1764821.34997 4897058.789997, 1764818.68 4897058.5, 1764812.591783 4897057.108204, 1764819.560837 4896999.356852, 1764801.447089 4896996.63796, 1764802.126355 4896987.574986, 1764827.938445 4896990.067304, 1764830.429086 4896964.011253, 1764832.740144 4896964.29157, 1764832.226208 4896968.528816, 1764833.728522 4896968.674128, 1764833.726376 4896968.721375, 1764832.22 4896968.58, 1764823.96 4897035.76, 1764826.244162 4897035.937929, 1764826.243892 4897035.940238, 1764823.961426 4897035.762083, 1764821.34997 4897058.789997)))
`

I am unable to fix with no algorithms cause by Exception here:

```
java.lang.IllegalArgumentException: Invalid number of points in LinearRing (found 3 - must be 0 or >= 4)
	at org.locationtech.jts.geom.LinearRing.validateConstruction(LinearRing.java:94)
	at org.locationtech.jts.geom.LinearRing.<init>(LinearRing.java:85)
	at org.locationtech.jts.geom.GeometryFactory.createLinearRing(GeometryFactory.java:356)
	at org.locationtech.jts.io.WKTReader.readLinearRingText(WKTReader.java:879)
	at org.locationtech.jts.io.WKTReader.readPolygonText(WKTReader.java:917)
	at org.locationtech.jts.io.WKTReader.readMultiPolygonText(WKTReader.java:974)
	at org.locationtech.jts.io.WKTReader.readGeometryTaggedText(WKTReader.java:827)
	at org.locationtech.jts.io.WKTReader.readGeometryTaggedText(WKTReader.java:785)
	at org.locationtech.jts.io.WKTReader.read(WKTReader.java:233)
	at org.locationtech.jts.io.WKTReader.read(WKTReader.java:214)
	at geometry.test.GeometryTest.testFixGeometry(GeometryTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:141)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

Here the code throwing this exception:

https://github.com/locationtech/jts/blob/349d5456c8ee58e4f5a911e3ee4ad3069ce9c929/modules/core/src/main/java/org/locationtech/jts/geom/LinearRing.java#L92-L95

This is a test project I just created with the issue https://github.com/Cavva79/invalid-linear-ring

How I fix it while reading the wkt?

**Comment by dr-jts** [comment]
That's a tricky one.  There is currently no way to fix this on-the-fly.

It might be nice to have a flag on the `WKTWriter` that would cause rings with too few points to be fixed automatically, so at least they can be read, even though they will be invalid.

**Comment by Cavva79** [comment]
Hi @dr-jts,
the problem is that there is no WKTWriter on my code. It is Oracle that create the wkt and those geometries are not fixed in first place before to be saved (it is out of our scope). 
It would be nice WKTReader can be configured to excludes invalid geometries in collections, wouldn't be?

**Comment by dr-jts** [comment]
WKTReader can read *most* invalid geometries.   The only kind it can't read are ones with rings that at "structurally invalid" due to having fewer than 4 points.  

I think the best solution for this is as I suggested above.  Allow WKTReader to "pad" short rings with extra (duplicate) points to allow the invalid rings to be constructed.  This should probably be optional and enabled by a flag, to avoid breaking older code.

**Comment by Cavva79** [comment]
Do you think the GeometyFactory might be a good place where to put this option?

**Comment by dr-jts** [comment]
Related [sf issue](https://github.com/r-spatial/sf/issues/1589).

**Comment by dr-jts** [comment]
Another option is to lower the limit on the number of points needed for a `LinearRing`.  I think it can be lowered to 3 with no problems, and that will solve this issue.  The ring will still be invalid, but at least it can be represented as a JTS geometry, which is a good design goal.

It's possible that the limit could be lowered to 2 points, but not sure if this will cause problems with some code.

**Comment by Cavva79** [comment]
Yes, this would be an option. 
I don't understand if allowing all geos to be constructed is a problem.
It wouldn't be better to mark those geos as invalid?
Then who's using that geo knows how to handle it.
If this is the path we choose, I may code the pull request.

**Comment by dr-jts** [comment]
I am about to make a PR to decrease the minimum number of points for a LinearRing. 

There is no mechanism in JTS to "mark a geometry as invalid".  That would be a major change.

**Comment by dr-jts** [comment]
PR #682 should resolve this issue.  You can now read the geometry containing the invalid ring, and fix it (one way to do this is to call `buffer(0)` on it.

**Comment by Cavva79** [comment]
Thanks a lot @dr-jts 
the fix is working great. Then I can repair the invalid geometry either with `.buffer(0)` or `geos.union(geos)`.
Actually the read geometry is seems invalid cause by the LinearRing with only 3 points.
Checked it with this commit Cavva79/invalid-linear-ring@d1d8892

**Comment by Cavva79** [comment]
Closing, resolved
