### ISSUE TITLE
WKTReader - issue with EMPTY Multipoint (ParseException) 

### ISSUE THREAD

**Issue by fkasel** [locationtech/jts#563]
The WKTReader throws an ParseException when reading the following WKT-String:
MULTIPOINT((10 10), EMPTY)

The stracktrace looks like:
Caused by: org.locationtech.jts.io.ParseException: Invalid number: EMPTY (line 1)
	at org.locationtech.jts.io.WKTReader.parseErrorWithLine(WKTReader.java:733)
	at org.locationtech.jts.io.WKTReader.getNextNumber(WKTReader.java:563)
	at org.locationtech.jts.io.WKTReader.getCoordinate(WKTReader.java:290)
	at org.locationtech.jts.io.WKTReader.getCoordinateSequence(WKTReader.java:355)
	at org.locationtech.jts.io.WKTReader.readMultiPointText(WKTReader.java:895)
	at org.locationtech.jts.io.WKTReader.readGeometryTaggedText(WKTReader.java:821)
	at org.locationtech.jts.io.WKTReader.readGeometryTaggedText(WKTReader.java:785)
	at org.locationtech.jts.io.WKTReader.read(WKTReader.java:233)
	at org.locationtech.jts.io.WKTReader.read(WKTReader.java:214)

The issue was found in version 1.16.1.
In the older version (i.e. 1.13.), the were no problems with this WKT-String.

**Comment by dr-jts** [comment]
Fixed by #575
