### ISSUE TITLE
Unknown unwrap conversion requested: org.locationtech.jts.geom.Geometry to [B [VARBINARY]

### ISSUE THREAD

**Issue by JoshiElijah** [locationtech/jts#579]
Hi, 
       when am trying to save List<Double> using converter containing the geometry data, am facing the unwrap exception.
 ```
@Column(columnDefinition = "Geometry")
 @Convert(converter = ListDoubleToPolygon.class)
  private List<Double> value; 
```

```
@Override
	public Geometry convertToDatabaseColumn(List<Double> attribute) {
		GeometryFactory factory = new GeometryFactory();
		Coordinate[] coordinates = new Coordinate[attribute.size() / 2];
		int count = 0;
		for(int i = 0; i < attribute.size(); i=i+2)
		{
			Coordinate coordinate = new Coordinate(attribute.get(i), attribute.get(i+1));
			coordinates[count++] = coordinate;
		}
		
		return factory.createPolygon(coordinates);
	}
```

Am new to this jts processing, i dont even know whether i can post it here or not. Any guidance on how i can address the problem.

**Comment by dr-jts** [comment]
Not sure if this is a JTS issue or not.  A stack trace would help to determine that.

**Comment by JoshiElijah** [comment]
`
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.1.RELEASE)

2020-08-27 08:25:54.070  INFO 1676 --- [           main] c.c.HibernateBasicTypeApplication        : Starting HibernateBasicTypeApplication on LAPTOP-DARU1PKF with PID 1676 (C:\Users\Joshi\Desktop\AIXM\Sts_Workspace_Project\HibernateBasicType\target\classes started by Joshi in C:\Users\Joshi\Desktop\AIXM\Sts_Workspace_Project\HibernateBasicType)
2020-08-27 08:25:54.074  INFO 1676 --- [           main] c.c.HibernateBasicTypeApplication        : No active profile set, falling back to default profiles: default
2020-08-27 08:25:54.483  INFO 1676 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2020-08-27 08:25:54.537  INFO 1676 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 45ms. Found 1 JPA repository interfaces.
2020-08-27 08:25:55.079  INFO 1676 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2020-08-27 08:25:55.145  INFO 1676 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.4.17.Final
2020-08-27 08:25:55.253  INFO 1676 --- [           main] o.h.spatial.integration.SpatialService   : HHH80000001: hibernate-spatial integration enabled : true
2020-08-27 08:25:55.289  INFO 1676 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
2020-08-27 08:25:55.392  INFO 1676 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2020-08-27 08:25:55.513  INFO 1676 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2020-08-27 08:25:55.535  INFO 1676 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
2020-08-27 08:25:56.228 DEBUG 1676 --- [           main] org.hibernate.SQL                        : drop table if exists office_employee cascade
Hibernate: drop table if exists office_employee cascade
2020-08-27 08:25:56.245 DEBUG 1676 --- [           main] org.hibernate.SQL                        : drop sequence if exists hibernate_sequence
Hibernate: drop sequence if exists hibernate_sequence
2020-08-27 08:25:56.249 DEBUG 1676 --- [           main] org.hibernate.SQL                        : create sequence hibernate_sequence start 1 increment 1
Hibernate: create sequence hibernate_sequence start 1 increment 1
2020-08-27 08:25:56.255 DEBUG 1676 --- [           main] org.hibernate.SQL                        : create table office_employee (id int8 not null, value Geometry, primary key (id))
Hibernate: create table office_employee (id int8 not null, value Geometry, primary key (id))
2020-08-27 08:25:56.265  INFO 1676 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2020-08-27 08:25:56.273  INFO 1676 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2020-08-27 08:25:56.653  INFO 1676 --- [           main] c.c.HibernateBasicTypeApplication        : Started HibernateBasicTypeApplication in 2.922 seconds (JVM running for 3.881)
2020-08-27 08:25:56.684 DEBUG 1676 --- [           main] org.hibernate.SQL                        : select nextval ('hibernate_sequence')
Hibernate: select nextval ('hibernate_sequence')
2020-08-27 08:25:56.709 DEBUG 1676 --- [           main] org.hibernate.SQL                        : insert into office_employee (value, id) values (?, ?)
Hibernate: insert into office_employee (value, id) values (?, ?)
2020-08-27 08:25:56.713 TRACE 1676 --- [           main] o.h.type.descriptor.sql.BasicBinder      : binding parameter [1] as [VARBINARY] - [POLYGON ((57.0833333333333 -40, 52.85 -41.7833333333333, 48.4666666666667 -41.3333333333333, 44.0333333333333 -40, 42.6 -37, 40.7333333333333 -37.1833333333333, 41.4 -30.05, 43.5166666666667 -21.1333333333333, 56.6666666666667 -21.1333333333333, 57.0833333333333 -40))]
2020-08-27 08:25:56.728  INFO 1676 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-08-27 08:25:56.740 ERROR 1676 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at com.configuration.HibernateBasicTypeApplication.main(HibernateBasicTypeApplication.java:34) [classes/:na]
Caused by: org.springframework.orm.jpa.JpaSystemException: Unknown unwrap conversion requested: org.locationtech.jts.geom.Geometry to [B; nested exception is org.hibernate.HibernateException: Unknown unwrap conversion requested: org.locationtech.jts.geom.Geometry to [B
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:353) ~[spring-orm-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:255) ~[spring-orm-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:538) ~[spring-orm-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:632) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:386) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:178) ~[spring-data-jpa-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at com.sun.proxy.$Proxy66.save(Unknown Source) ~[na:na]
	at com.configuration.HibernateBasicTypeApplication.run(HibernateBasicTypeApplication.java:70) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	... 5 common frames omitted
Caused by: org.hibernate.HibernateException: Unknown unwrap conversion requested: org.locationtech.jts.geom.Geometry to [B
	at org.hibernate.type.descriptor.java.AbstractTypeDescriptor.unknownUnwrap(AbstractTypeDescriptor.java:98) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.spatial.JTSGeometryJavaTypeDescriptor.unwrap(JTSGeometryJavaTypeDescriptor.java:70) ~[hibernate-spatial-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.spatial.JTSGeometryJavaTypeDescriptor.unwrap(JTSGeometryJavaTypeDescriptor.java:26) ~[hibernate-spatial-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.type.descriptor.sql.VarbinaryTypeDescriptor$1.doBind(VarbinaryTypeDescriptor.java:45) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.type.descriptor.sql.BasicBinder.bind(BasicBinder.java:73) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.type.descriptor.converter.AttributeConverterSqlTypeDescriptorAdapter$1.bind(AttributeConverterSqlTypeDescriptorAdapter.java:88) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:276) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:271) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.type.AbstractSingleColumnStandardBasicType.nullSafeSet(AbstractSingleColumnStandardBasicType.java:39) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.dehydrate(AbstractEntityPersister.java:2948) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3245) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3779) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:107) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[na:1.8.0_191]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:348) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:102) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1360) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:451) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3210) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2378) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:447) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:40) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101) ~[hibernate-core-5.4.17.Final.jar:5.4.17.Final]
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:534) ~[spring-orm-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	... 21 common frames omitted

2020-08-27 08:25:56.742  INFO 1676 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2020-08-27 08:25:56.744  INFO 1676 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2020-08-27 08:25:56.747  INFO 1676 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
`

**Comment by dr-jts** [comment]
This is probably a Hibernate error, so you might want to investigate that.
