### ISSUE TITLE
Testbuilder doesn't work

### ISSUE THREAD

**Issue by rukemn** [locationtech/jts#631]
I pulled the repository and clean installed via maven. Afterwards I wanted to start the TestBuilder as described in 
[https://github.com/locationtech/jts/blob/master/doc/JTSTestBuilder.md](url)
via the command  

`java -jar modules/app/target/JTSTestBuilder.jar` . 

I received the following error message : 

> java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Double (java.lang.Integer and java.lang.Double are in module java.base of loader 'bootstrap')
	at java.base/java.lang.Double.compareTo(Double.java:49)
	at java.desktop/javax.swing.SpinnerNumberModel.incrValue(SpinnerNumberModel.java:362)
	at java.desktop/javax.swing.SpinnerNumberModel.getPreviousValue(SpinnerNumberModel.java:401)
	at java.desktop/javax.swing.plaf.basic.BasicSpinnerUI.updateEnabledState(BasicSpinnerUI.java:514)
	at java.desktop/javax.swing.plaf.basic.BasicSpinnerUI.updateEnabledState(BasicSpinnerUI.java:494)
	at java.desktop/javax.swing.plaf.basic.BasicSpinnerUI$Handler.stateChanged(BasicSpinnerUI.java:1084)
	at java.desktop/javax.swing.JSpinner.fireStateChanged(JSpinner.java:461)
	at java.desktop/javax.swing.JSpinner$ModelListener.stateChanged(JSpinner.java:388)
	at java.desktop/javax.swing.AbstractSpinnerModel.fireStateChanged(AbstractSpinnerModel.java:120)
	at java.desktop/javax.swing.SpinnerNumberModel.setValue(SpinnerNumberModel.java:460)
	at org.locationtech.jtstest.testbuilder.LayerStylePanel.setLayer(LayerStylePanel.java:105)
	at org.locationtech.jtstest.testbuilder.LayerListPanel.setLayerFocus(LayerListPanel.java:210)
	at org.locationtech.jtstest.testbuilder.LayerListPanel.populateList(LayerListPanel.java:184)
	at org.locationtech.jtstest.testbuilder.JTSTestBuilderFrame.setModel(JTSTestBuilderFrame.java:252)
	at org.locationtech.jtstest.testbuilder.JTSTestBuilder.initFrame(JTSTestBuilder.java:100)
	at org.locationtech.jtstest.testbuilder.JTSTestBuilder.main(JTSTestBuilder.java:132)

I am receiving the same Message when executing the main method from the JTSTestBuilder class directly from the source code.
Is there anything I overlooked or is it an actual bug?

**Comment by dr-jts** [comment]
It's working for me off master.  What Java version are you using?

**Comment by rukemn** [comment]
I have tried it with 

> java version 1.8.0_201
as well as with 
> java version 11.0.4

**Comment by dr-jts** [comment]
It looks like `SpinnerNumberModel` is a bit loose about how it manages the number type, and the calls in `LayerStylePanel` weren't quite consistent with the types in the constructor and the value setters.  I've made a small fix now.  It works for me - but then it worked for me before as well.  Can you test and report back?

**Comment by dr-jts** [comment]
What system are you running this on?  I'm on Windows.  I wonder if Java behaves slightly differently on different platforms?

**Comment by rukemn** [comment]
With the new commit it's working for me now. Thank you for the quick response.

I was running on an Ubuntu 18.04.5 maschine.
