### ISSUE TITLE
TopologyException intersecting polygons with redundant points

### ISSUE THREAD

**Issue by anragab** [locationtech/jts#760]
I am trying to intersect these two polygons but I am getting an exception back.

**Polygon A**

```WKT
POLYGON ((0 1.991, 0 13, 1750 13, 1750 1.991, 0 1.991))
```

**Polygon B**

```WKT
POLYGON ((900 2, 1250 2, 1750 4, 1750 10, 1380 15, 900 15, 900 2, 
          900 2, 1250 2, 1750 4, 1750 10, 1380 15, 900 15, 900 2))
```

*last 7 points are same as first 7

**Expected Result**

```WKT
POLYGON ((900 2, 1250 2, 1750 4, 1750 10, 1528 13, 900 13, 900 2))
```

**Result**
```
org.locationtech.jts.geom.TopologyException: found non-noded intersection between LINESTRING ( 900 2, 1250 2 ) and LINESTRING ( 900 2, 1250 2 ) [ (900.0, 2.0, NaN) ]
	at org.locationtech.jts.noding.FastNodingValidator.checkValid(FastNodingValidator.java:140) ~[jts-core-1.18.1.jar:na]
	at org.locationtech.jts.geomgraph.EdgeNodingValidator.checkValid(EdgeNodingValidator.java:81) ~[jts-core-1.18.1.jar:na]
	at org.locationtech.jts.geomgraph.EdgeNodingValidator.checkValid(EdgeNodingValidator.java:46) ~[jts-core-1.18.1.jar:na]
	at org.locationtech.jts.operation.overlay.OverlayOp.computeOverlay(OverlayOp.java:231) ~[jts-core-1.18.1.jar:na]
	at org.locationtech.jts.operation.overlay.OverlayOp.getResultGeometry(OverlayOp.java:183) ~[jts-core-1.18.1.jar:na]
	at org.locationtech.jts.operation.overlay.OverlayOp.overlayOp(OverlayOp.java:86) ~[jts-core-1.18.1.jar:na]
	at org.locationtech.jts.operation.overlay.snap.SnapIfNeededOverlayOp.getResultGeometry(SnapIfNeededOverlayOp.java:75) ~[jts-core-1.18.1.jar:na]
	at org.locationtech.jts.operation.overlay.snap.SnapIfNeededOverlayOp.overlayOp(SnapIfNeededOverlayOp.java:37) ~[jts-core-1.18.1.jar:na]
	at org.locationtech.jts.geom.GeometryOverlay.overlay(GeometryOverlay.java:76) ~[jts-core-1.18.1.jar:na]
	at org.locationtech.jts.geom.GeometryOverlay.intersection(GeometryOverlay.java:119) ~[jts-core-1.18.1.jar:na]
	at org.locationtech.jts.geom.Geometry.intersection(Geometry.java:1328) ~[jts-core-1.18.1.jar:na]
```

**Comment by dr-jts** [comment]
If a polygon has duplicate segments then it is invalid.  Overlay only works with valid inputs.

It would help if you provide WKT for example data.

**Comment by anragab** [comment]
@dr-jts can the error messages be improved for that? I have updated the description. There is no WKT source file for the data.

**Comment by dr-jts** [comment]
> can the error messages be improved for that? 

That would incur the additional cost of running a validity check, which we don't want to do.
