### ISSUE TITLE
ConcaveHullOfPolygons.concaveHullByLengthRatio ends in "Unable to find a convex corner"

### ISSUE THREAD

**Issue by ilvez** [locationtech/jts#921]
[Following request](https://gis.stackexchange.com/questions/439271/simplify-multipolygon-removing-small-gaps-in-postgis#comment717806_439274) to share geometries that cause "Unable to find a convex corner". Although the context was PostGIS, but I'm assuming that the answerer and the request is related to this project as well. I don't have currently PostGIS 3.3 to test this upon & was more interested in JTS solution at this point. If this request is not related then feel free to close it :smile: Note also, that I'm not original poster of this question in StackExchange.

I'm using jts-core & jts-io-common versions 1.19.0.

You can find the runnable example [here](https://gist.github.com/ilvez/6c9367fb22caa79647070ec7b9ce8a59), it contains geojsons which cause this issue.

Stacktrace running that program:
```
Exception in thread "main" java.lang.IllegalStateException: Unable to find a convex corner
        at org.locationtech.jts.triangulate.polygon.PolygonEarClipper.compute(PolygonEarClipper.java:169)
        at org.locationtech.jts.triangulate.polygon.PolygonEarClipper.triangulate(PolygonEarClipper.java:61)
        at org.locationtech.jts.triangulate.polygon.ConstrainedDelaunayTriangulator.triangulatePolygon(ConstrainedDelaunayTriangulator.java:107)
        at org.locationtech.jts.triangulate.polygon.ConstrainedDelaunayTriangulator.compute(ConstrainedDelaunayTriangulator.java:87)
        at org.locationtech.jts.triangulate.polygon.ConstrainedDelaunayTriangulator.getTriangles(ConstrainedDelaunayTriangulator.java:77)
        at org.locationtech.jts.algorithm.hull.ConcaveHullOfPolygons.buildHullTris(ConcaveHullOfPolygons.java:303)
        at org.locationtech.jts.algorithm.hull.ConcaveHullOfPolygons.getHull(ConcaveHullOfPolygons.java:274)
        at org.locationtech.jts.algorithm.hull.ConcaveHullOfPolygons.concaveHullByLengthRatio(ConcaveHullOfPolygons.java:140)
        at geometer.UnableToFindConvexCornerExample.main(UnableToFindConvexCornerExample.java:24)
```

**Comment by dr-jts** [comment]
Thanks, confirmed this is a reproducer.  Provided below as a WKT geometry.
```
MULTIPOLYGON (((27.182707766 58.27047915, 27.182731479 58.270490512, 27.182763932 58.270494733, 27.182853667 58.270458781, 27.182993413 58.270385263, 27.183049126 58.270363645, 27.183072544 58.270356587, 27.183086082 58.270349687, 27.183159558 58.270309377, 27.183441965 58.270128471, 27.183640212 58.270018883, 27.183738477 58.269960245, 27.183755566 58.269943547, 27.183762324 58.269916323, 27.183773416 58.269897439, 27.183793741 58.269874998, 27.183864539 58.269842844, 27.183914559 58.26982811, 27.184031213 58.269772876, 27.18419808 58.269669106, 27.184395311 58.269512351, 27.184450231 58.269434663, 27.184458955 58.269419794, 27.184471597 58.269389725, 27.184485555 58.269347758, 27.184492994 58.269314853, 27.184494432 58.26929675, 27.184474963 58.269260564, 27.184457743 58.269245535, 27.183837561 58.26924461, 27.183749514 58.269251937, 27.181359491 58.269268497, 27.181111839 58.26927469, 27.180981402 58.269282985, 27.1808911 58.269293693, 27.180815688 58.269327668, 27.180768303 58.269388716, 27.18077735 58.269773291, 27.180784328 58.26995873, 27.180813818 58.27000015, 27.180855452 58.270036231, 27.180862194 58.270067523, 27.180912571 58.270085139, 27.180965275 58.270098293, 27.181041428 58.270110411, 27.181188584 58.27012291, 27.181393927 58.270135572, 27.181510915 58.270144601, 27.181620665 58.270158486, 27.181661328 58.270161064, 27.181810886 58.270190761, 27.18187508 58.270191312, 27.182021744 58.270251373, 27.182142671 58.270294639, 27.18220981 58.270314622, 27.182260222 58.270326934, 27.182380483 58.270345768, 27.182423717 58.270344686, 27.182479526 58.270360099, 27.182533492 58.27038913, 27.182606675 58.270419388, 27.182707766 58.27047915), (27.18399466 58.269359866, 27.183988636 58.269370624, 27.183965777 58.26938387, 27.183942004 58.269386982, 27.18391477 58.269387663, 27.183894304 58.269391501, 27.183861008 58.269394941, 27.183828701 58.269392334, 27.18381041 58.269384343, 27.183796739 58.269374618, 27.183796977 58.26936023, 27.1838087 58.269346454, 27.183844717 58.269320204, 27.183876417 58.269316085, 27.183899297 58.269316322, 27.183935915 58.269321338, 27.183967142 58.269329005, 27.183987728 58.26933595, 27.184000103 58.269342652, 27.184004397 58.269346769, 27.184004761 58.269350805, 27.184000156 58.269356493, 27.18399466 58.269359866), (27.182562372 58.2701663, 27.182550481 58.270168754, 27.182522129 58.270170273, 27.182505319 58.270169255, 27.182474617 58.270163641, 27.182457955 58.2701548, 27.182450291 58.270143576, 27.182449782 58.270137926, 27.182452822 58.270133805, 27.182467997 58.270126145, 27.182489421 58.270121564, 27.182526907 58.270121075, 27.182554821 58.27012604, 27.182582644 58.270135681, 27.182587011 58.270138717, 27.182591314 58.270144812, 27.182591247 58.270151645, 27.182585823 58.270157713, 27.182574207 58.270163217, 27.182562372 58.2701663)), ((27.180796966 58.270998752, 27.180846728 58.271043619, 27.180922976 58.271070027, 27.180961686 58.271077418, 27.180975624 58.271088215, 27.181057505 58.271116549, 27.181078578 58.271121326, 27.181468375 58.271189239, 27.181573737 58.271194155, 27.181657898 58.271189084, 27.181724303 58.271172502, 27.182195366 58.270887017, 27.182519836 58.270661646, 27.182590458 58.270570712, 27.182236145 58.270430815, 27.182031548 58.270352609, 27.181952454 58.270330588, 27.181846662 58.270307616, 27.181839414 58.270285866, 27.181818404 58.270262841, 27.181792396 58.270254413, 27.181620097 58.270243082, 27.181512745 58.270208465, 27.181346222 58.270208225, 27.181173077 58.270181814, 27.180866279 58.270173486, 27.180791437 58.270191087, 27.180775199 58.2702021, 27.180761715 58.270217178, 27.180748668 58.270237099, 27.180740718 58.270285207, 27.180719309 58.270318371, 27.180717341 58.270340083, 27.180720609 58.270363102, 27.180721178 58.270382683, 27.180759777 58.270428638, 27.180796407 58.270450823, 27.180854893 58.27048082, 27.180900464 58.270499995, 27.18091484 58.270508085, 27.181869214 58.270618507, 27.18204559 58.27063342, 27.182127689 58.270635771, 27.182170573 58.270642159, 27.182182478 58.270649322, 27.182190236 58.270672947, 27.18218141 58.270699954, 27.182159879 58.270710919, 27.182135051 58.270717473, 27.181072996 58.270601027, 27.180997891 58.270657376, 27.180978714 58.270681225, 27.180970973 58.270710812, 27.180973595 58.270722881, 27.180964423 58.27073848, 27.180954119 58.2707453, 27.180836629 58.270912549, 27.180800578 58.270957404, 27.180794896 58.270983343, 27.18079465 58.270991979, 27.180796966 58.270998752)))
```

**Comment by dr-jts** [comment]
This is caused by a known bug in `PolygonHoleJoiner`, which can cause self-crossing linework to be produced for certain input situations.

**Comment by dr-jts** [comment]
It turns out this is caused by another bug (or really a design flaw, involving the unnecessary use of a tolerance value for coordinate comparison).  The bug has been fixed, and will be rolled out into JTS and GEOS soon.

**Comment by ilvez** [comment]
Thanks for fixing this either way. :bow: 

Was this the fix? https://github.com/libgeos/geos/commit/1e937361df14e569f7428f5c0b4df55fd5ff2062

Should I close it now or should I wait for release and test it out or you are closing the ticket yourself?

**Comment by dr-jts** [comment]
The fix is still in progress in JTS, as part of a larger rewrite of the `PolygonHoleJoiner`.  Once that's in place, it will be ported to GEOS.  Might be early Jan for that (earlier if we can).

This issue can be closed when it lands in GEOS.
