### ISSUE TITLE
Overlay intersection of Polygon/Polygon throws TopologyException

### ISSUE THREAD

**Issue by pking1997** [locationtech/jts#938]
I am trying to intersect these two polygons,both polygon are valid, but I am getting an exception back.

### Polygon1
POLYGON ((117.25669107621917 31.88087184799008, 117.25520887212771 31.880802859126742, 117.25442734633403 31.880814357274257, 117.25389285455559 31.881094145083686, 117.2537311595638 31.882109805947422, 117.25282387099872 31.88289549810332, 117.25232081991314 31.883106292408414, 117.25170997216635 31.88297215063427, 117.25181327729999 31.882174961164015, 117.25170098911124 31.881339437799713, 117.25098234470326 31.88026627729769, 117.25034005626362 31.880231782643566, 117.24997624253209 31.880511572239733, 117.25058709027887 31.881523406903888, 117.25026370029528 31.88170737563706, 117.2498864119811 31.881761033114348, 117.24945971686385 31.88144292046647, 117.24871861481812 31.881032821801625, 117.24814369929173 31.88112097400662, 117.24808081790603 31.881833853925908, 117.24808530943359 31.882669372761757, 117.24629768146873 31.88076836467552, 117.24537242679345 31.879837009562078, 117.24488285029051 31.87930808761019, 117.24463132474771 31.878821323394163, 117.24814369929173 31.878487869243305, 117.24807183485093 31.8753909035069, 117.24807183485093 31.875298912818067, 117.24805386874074 31.868740504315234, 117.24807632637848 31.863159161314687, 117.24804937721319 31.85753914012856, 117.25040293764933 31.857642649784946, 117.25284632863647 31.857945510698194, 117.25647997442432 31.858953761942487, 117.25741870368226 31.85924511764295, 117.2574501443751 31.859904498163512, 117.25673149996712 31.880664881243572, 117.25669107621917 31.88087184799008))

### Polygon2
POLYGON ((117.25733381625201 31.863265014673992, 117.25105232709294 31.86347350418914, 117.24835452233238 31.87129622640433, 117.2489365393494 31.870178694603474, 117.25698972630828 31.873205172792094, 117.25694481874807 31.87450247385353, 117.25694481874807 31.874502473853532, 117.25733381625201 31.863265014673992))

### version
1.18.1

### result
Exception in thread "main" org.locationtech.jts.geom.TopologyException: found non-noded intersection between LINESTRING ( 117.25726597194272 31.865224918397033, 117.2574501443751 31.859904498163512 ) and LINESTRING ( 117.25733381625201 31.863265014673992, 117.25105232709294 31.86347350418914 ) [ (117.25733381625201, 31.863265014673992, NaN) ]
	at org.locationtech.jts.noding.FastNodingValidator.checkValid(FastNodingValidator.java:140)
	at org.locationtech.jts.geomgraph.EdgeNodingValidator.checkValid(EdgeNodingValidator.java:81)
	at org.locationtech.jts.geomgraph.EdgeNodingValidator.checkValid(EdgeNodingValidator.java:46)
	at org.locationtech.jts.operation.overlay.OverlayOp.computeOverlay(OverlayOp.java:231)
	at org.locationtech.jts.operation.overlay.OverlayOp.getResultGeometry(OverlayOp.java:183)
	at org.locationtech.jts.operation.overlay.OverlayOp.overlayOp(OverlayOp.java:86)
	at org.locationtech.jts.operation.overlay.snap.SnapIfNeededOverlayOp.getResultGeometry(SnapIfNeededOverlayOp.java:75)
	at org.locationtech.jts.operation.overlay.snap.SnapIfNeededOverlayOp.overlayOp(SnapIfNeededOverlayOp.java:37)
	at org.locationtech.jts.geom.GeometryOverlay.overlay(GeometryOverlay.java:76)
	at org.locationtech.jts.geom.GeometryOverlay.intersection(GeometryOverlay.java:119)
	at org.locationtech.jts.geom.Geometry.intersection(Geometry.java:1328)

### code
        String wkt1 = "POLYGON ((117.25669107621917 31.88087184799008, 117.25520887212771 31.880802859126742, 117.25442734633403 31.880814357274257, 117.25389285455559 31.881094145083686, 117.2537311595638 31.882109805947422, 117.25282387099872 31.88289549810332, 117.25232081991314 31.883106292408414, 117.25170997216635 31.88297215063427, 117.25181327729999 31.882174961164015, 117.25170098911124 31.881339437799713, 117.25098234470326 31.88026627729769, 117.25034005626362 31.880231782643566, 117.24997624253209 31.880511572239733, 117.25058709027887 31.881523406903888, 117.25026370029528 31.88170737563706, 117.2498864119811 31.881761033114348, 117.24945971686385 31.88144292046647, 117.24871861481812 31.881032821801625, 117.24814369929173 31.88112097400662, 117.24808081790603 31.881833853925908, 117.24808530943359 31.882669372761757, 117.24629768146873 31.88076836467552, 117.24537242679345 31.879837009562078, 117.24488285029051 31.87930808761019, 117.24463132474771 31.878821323394163, 117.24814369929173 31.878487869243305, 117.24807183485093 31.8753909035069, 117.24807183485093 31.875298912818067, 117.24805386874074 31.868740504315234, 117.24807632637848 31.863159161314687, 117.24804937721319 31.85753914012856, 117.25040293764933 31.857642649784946, 117.25284632863647 31.857945510698194, 117.25647997442432 31.858953761942487, 117.25741870368226 31.85924511764295, 117.2574501443751 31.859904498163512, 117.25673149996712 31.880664881243572, 117.25669107621917 31.88087184799008))";
        String wkt2 = "POLYGON ((117.25733381625201 31.863265014673992, 117.25105232709294 31.86347350418914, 117.24835452233238 31.87129622640433, 117.2489365393494 31.870178694603474, 117.25698972630828 31.873205172792094, 117.25694481874807 31.87450247385353, 117.25694481874807 31.874502473853532, 117.25733381625201 31.863265014673992))";
   
        GeometryFactory geometryFactory = new GeometryFactory();
        WKTReader reader = new WKTReader(geometryFactory);
        Geometry geometry1 =  reader.read(wkt1);
        Geometry geometry2 =  reader.read(wkt1);
        if(geometry1.isValid()&&geometry2.isValid()){
            Geometry intersection = geometry1.intersection(geometry2);
            System.out.println(intersection.toText());
        }

### Tried another way
       GeometryFactory geometryFactory = new GeometryFactory();
        WKTReader reader = new WKTReader(geometryFactory);
        Geometry geometry1 =  reader.read(wkt1);
        Geometry geometry2 =  reader.read(wkt1);
        if(geometry1.isValid()&&geometry2.isValid()){
            //get exception
            Geometry intersection = geometry1.buffer(0).intersection(geometry2.buffer(0));
            System.out.println(intersection.toText());
           //its ok
           Geometry intersection = geometry2.buffer(0).intersection(geometry1.buffer(0));
            System.out.println(intersection.toText());
        }

**Comment by pking1997** [comment]
I guess overlapping edges caused the anomaly,but isValid() turn true
![image](https://user-images.githubusercontent.com/41529693/205620919-8715c2c3-c03c-4d20-bda6-f41da9a2cee9.png)

**Comment by dr-jts** [comment]
This is occurring due to well-known robustness issues with the old overlay code.  Version 1.18 introduced a new OverlayNG algorithm, which is able to handle this case.  You need to enable use of this code via a [system property](https://github.com/locationtech/jts/blob/master/USING.md#jts-system-properties).

**Comment by pking1997** [comment]
I hugely appreciate you answering it,it work

**Comment by pking1997** [comment]
> This is occurring due to well-known robustness issues with the old overlay code. Version 1.18 introduced a new OverlayNG algorithm, which is able to handle this case. You need to enable use of this code via a [system property](https://github.com/locationtech/jts/blob/master/USING.md#jts-system-properties).

I hugely appreciate you answering it,it work

**Comment by pking1997** [comment]
But it works fine when I use OverlayNGRobust. However, it doesn’t seem like a good idea to replace all geometry.intersection calls with OverlayNGRobust.

<img width="1600" height="1600" alt="Image" src="https://github.com/user-attachments/assets/deeb0a68-ed6a-44b3-9d0d-510a3caf8bcc" />

**Comment by dr-jts** [comment]
> But it works fine when I use OverlayNGRobust. However, it doesn’t seem like a good idea to replace all geometry.intersection calls with OverlayNGRobust.

Why do you not think so?

OverlayNG is going to be the default overlay code in the next release. So it's fine to use it ahead of time.

See also https://github.com/locationtech/jts/issues/1086#issuecomment-2401126978
